[tox]
envlist =
    ruff
    py{310,311,312,313,314}-dj52-cms{50,51}
    py{312,313,314}-dj{60,61}-cms51

skip_missing_interpreters=True

[testenv]
deps =
    -r{toxinidir}/tests/requirements/base.txt
    dj52: Django>=5.2,<6.0
    dj60: Django>=6.0,<6.1
    dj61: Django>=6.1,<6.2
    cms50: django-cms>=5.0,<5.1
    cms51: django-cms>=5.1,<5.2
commands =
    {envpython} --version
    {env:COMMAND:coverage} erase
    {env:COMMAND:coverage} run tests/settings.py
    {env:COMMAND:coverage} report

[testenv:ruff]
deps = ruff
commands = ruff check
skip_install = true
