# Generated by Django 1.9.13 on 2017-05-03 07:36
import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('djangocms_googlemap', '0008_removed_null_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemapmarker',
            name='icon',
            field=filer.fields.image.FilerImageField(blank=True, help_text='A marker icon identifies a location on a map. By default, it uses a standard image from Google.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Icon'),
        ),
    ]
