# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_googlemap', '0009_googlemapmarker_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlemapmarker',
            name='icon',
            field=filer.fields.image.FilerImageField(blank=True, help_text='A marker icon identifies a location on a map. By default, it uses a standard image from Google.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.FILER_IMAGE_MODEL, verbose_name='Icon'),
        ),
    ]
