# Generated by Django 2.2.3 on 2019-07-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_googlemap', '0009_googlemapmarker_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlemapmarker',
            name='lat',
            field=models.FloatField(blank=True, help_text='Geographical latitude in degrees (e.g. "46.947973").', null=True, verbose_name='Latitude (lat)'),
        ),
        migrations.AlterField(
            model_name='googlemapmarker',
            name='lng',
            field=models.FloatField(blank=True, help_text='Geographical longitude in degrees (e.g. "7.447446").', null=True, verbose_name='Longitude (lng)'),
        ),
    ]
