# Generated by Django 4.2.1 on 2023-05-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_googlemap', '0010_auto_20190718_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemap',
            name='map_id',
            field=models.CharField(blank=True, help_text='Map ID of Cloud-based maps styling. See https://developers.google.com/maps/documentation/cloud-customization/overview', max_length=32, verbose_name='Map ID'),
        ),
    ]
